
[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200

[[redirects]]
  from = "/ext/open-client/steam/*"
  to = "steam://store/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/ext/open-client/epic/*"
  to = "com.epicgames.launcher://store/p/:splat"
  status = 301
  force = true
