
[[redirects]]
  from = "/arc-sw.js"
  to = "https://arc.io/arc-sw.js"
  status = 200

[[redirects]]
  from = "/ext/open-client/steam/:id"
  to = "steam://store/:id"
  status = 301
  force = true

[[redirects]]
  from = "/ext/open-client/epic/:id"
  to = "com.epicgames.launcher://store/p/:id"
  status = 301
  force = true
